### ISSUE TITLE
Error in optional argument model.args of pec

### ISSUE THREAD

**Issue by bentriom** [tagteam/pec#2]
Hello,

I'm trying to use the optional argument `model.args` of the function `pec`.  However, I may have detected an issue with the argument. This code example, whose basis has been found in the documentation, raises an error:

```R
set.seed(130971)
library(prodlim)
library(survival)

dat <- SimSurv(100)
# fit some candidate Cox models and compute the Kaplan-Meier estimate
Models <- list("Cox.X1"=coxph(Surv(time,status)~X1,data=dat,x=TRUE,y=TRUE),
               "Cox.X2"=coxph(Surv(time,status)~X2,data=dat,x=TRUE,y=TRUE),
               "Cox.X1.X2"=coxph(Surv(time,status)~X1+X2,data=dat,x=TRUE,y=TRUE))
# compute the apparent prediction error
PredError <- pec(object=Models,
                 formula=Surv(time,status)~X1+X2,
                 data=dat,
                 exact=TRUE,
                 cens.model="marginal",
                 splitMethod="none",
                 model.args=list(c("ties"="exact"), c("ties"="efron"), c("ties"="exact")),
                 B=0,
                 verbose=TRUE)
```

The error is:

```R
Error in model.args[[f]] : subscript out of bounds
```

I have investigated the source code of `pec`. 
The error is raised by line 677 of `pec.R`.
I think the error relies in the fact that the length of the list `object` is changed within the function. Indeed, a "Reference" model is added during the execution of the function (line 518), which renders the length of `model.args` inconsistent. If the argument is replaced by:

```R
model.args=list(c(), c("ties"="exact"), c("ties"="efron"), c("ties"="exact"))
```
the code doesn't raise any error.

Let me know if there is something wrong with my understanding of the use of the function.

Thanks!

**Comment by tagteam** [comment]
yes, I agree that this is confusing, but your explanation and understanding is correct. you can actively suppress the reference model by setting reference=FALSE. Note that most of the functionality of pec has been moved to the more active package riskRegression where the riskRegression::Score function corresponds to pec::pec. Let me know if you cannot work out your own use case with riskRegression instead

**Comment by bentriom** [comment]
Ok I see, thanks a lot for your answer !
